[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "mon-projet-icare"
version = "0.1.0"
dependencies = [
    "numpy",
    "pandas",
    "requests"
]

[tool.setuptools.packages.find]
where = ["src"]